version: 2
updates:
  # Enable version updates for npm dependencies in root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    # Group updates to reduce PR volume
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "ts-node"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "jest"
          - "mocha"
          - "chai"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "ts-node"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "jest"
          - "mocha"
          - "chai"
        update-types:
          - "minor"
          - "patch"
    # Rebase PRs automatically to keep them current
    rebase-strategy: "auto"
    # Only update to secure versions for major updates
    versioning-strategy: "increase-if-necessary"

  # Enable version updates for npm dependencies in electron directory
  - package-ecosystem: "npm"
    directory: "/electron"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "chore(electron)"
      prefix-development: "chore(electron)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "electron"
    # Group electron-specific updates
    groups:
      electron-framework:
        patterns:
          - "electron"
          - "electron-*"
        update-types:
          - "minor"
          - "patch"
      electron-dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint*"
        update-types:
          - "minor"
          - "patch"
      electron-ui-dependencies:
        patterns:
          - "react"
          - "react-*"
          - "@emotion/*"
        update-types:
          - "minor"
          - "patch"
    rebase-strategy: "auto"
    versioning-strategy: "increase-if-necessary"

  # Security updates - more frequent for critical fixes
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "npm"
    # Only security updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

  # Security updates for electron directory
  - package-ecosystem: "npm"
    directory: "/electron"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "security(electron)"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "npm"
      - "electron"
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "nydiokar"
    assignees:
      - "nydiokar"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    rebase-strategy: "auto" 