version: 2
updates:
  # Root directory npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    # Remove reviewers to allow auto-merge
    # reviewers:
    #   - "nydiokar"
    labels:
      - "dependencies"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge configuration
    commit-message:
      prefix: "chore"
      include: "scope"

  # Electron directory npm dependencies  
  - package-ecosystem: "npm"
    directory: "/electron"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    # Remove reviewers to allow auto-merge
    # reviewers:
    #   - "nydiokar"
    labels:
      - "dependencies"
      - "electron"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge configuration
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    # Remove reviewers to allow auto-merge
    # reviewers:
    #   - "nydiokar"
    labels:
      - "dependencies"
    # Enable auto-merge for minor and patch updates
    allow:
      - dependency-type: "all"
    # Auto-merge configuration
    commit-message:
      prefix: "chore"
      include: "scope" 